### ISSUE TITLE
aurelia-css-modules-loader NPM links here

### ISSUE THREAD

**Issue by jfstephe** [bryanrsmith/aurelia-binding-loader#5]
This confused the me substantially, as aurelia-css-modules-loader NPM links here. Can you unpublish/mark as superseded/or unlink the above npm module with this github repo?

**Comment by bryanrsmith** [comment]
That happened because I renamed the project (while generalizing its functionality). The old aurelia-css-modules package was marked as deprecated in npm, but I didn't want to unpublish it. I've published a new README with a deprecation warning. Thanks!
